# Classificação com dados desbalanceados

## Carregamento da base de dados

In [1]:
import pandas as pd
import random
import numpy as np

In [5]:
dataset = pd.read_csv('credit_data.csv')

In [6]:
dataset.shape

(2000, 5)

In [7]:
dataset.head()

i#clientid        income        age         loan  c#default
0           1  66155.925095  59.017015  8106.532131          0
1           2  34415.153966  48.117153  6564.745018          0
2           3  57317.170063  63.108049  8020.953296          0
3           4  42709.534201  45.751972  6103.642260          0
4           5  66952.688845  18.584336  8770.099235          1

In [8]:
dataset.dropna(inplace=True)
dataset.shape

(1997, 5)

In [11]:
import seaborn as sns
sns.countplot(x=dataset['c#default']);

ModuleNotFoundError: No module named 'seaborn'

In [ ]:
X = dataset.iloc[:, 1:4].values

In [ ]:
X.shape

(1997, 3)

In [ ]:
X

array([[6.61559251e+04, 5.90170151e+01, 8.10653213e+03],
       [3.44151540e+04, 4.81171531e+01, 6.56474502e+03],
       [5.73171701e+04, 6.31080495e+01, 8.02095330e+03],
       ...,
       [4.43114493e+04, 2.80171669e+01, 5.52278669e+03],
       [4.37560566e+04, 6.39717958e+01, 1.62272260e+03],
       [6.94365795e+04, 5.61526170e+01, 7.37883360e+03]])

In [ ]:
y = dataset.iloc[:, 4].values

In [ ]:
y.shape

(1997,)

In [ ]:
y

array([0, 0, 0, ..., 1, 0, 0])

## Subamostragem (undersampling) - Tomek links

- https://imbalanced-learn.readthedocs.io/en/stable/user_guide.html

In [12]:
from imblearn.under_sampling import TomekLinks

ModuleNotFoundError: No module named 'imblearn'

In [ ]:
tl = TomekLinks(sampling_strategy='majority')
X_under, y_under = tl.fit_resample(X, y)

In [ ]:
X_under.shape, y_under.shape

((1897, 3), (1897,))

In [ ]:
np.unique(y, return_counts=True)

(array([0, 1]), array([1714,  283]))

In [ ]:
np.unique(y_under, return_counts=True)

(array([0, 1]), array([1614,  283]))

## Sobreamostragem (oversampling) - SMOTE

In [ ]:
from imblearn.over_sampling import SMOTE

In [ ]:
smote = SMOTE(sampling_strategy='minority')
X_over, y_over = smote.fit_resample(X, y)

In [ ]:
X_over.shape, y_over.shape

((3428, 3), (3428,))

In [ ]:
np.unique(y, return_counts=True)

(array([0, 1]), array([1714,  283]))

In [ ]:
np.unique(y_over, return_counts=True)

(array([0, 1]), array([1714, 1714]))